name: arm

on:
  push:
  workflow_dispatch:

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build Obfuscator
        run: |
          tree

