name: main

on:
  #push:
  workflow_dispatch:

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build Obfuscator
        run: |
          git clone https://github.com/heroims/obfuscator.git
          cd obfuscator
          git checkout llvm-9.0.1
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_INCLUDE_TESTS=OFF ..
          make -j2

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: obfuscator/build
          retention-days: 30
