name: main2

on:
  workflow_dispatch:

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Download and Setup Zig
        run: |
          wget -O a.zip https://github.com/x20888450/main001/releases/download/Releases/a.zip || { echo 'Download failed'; exit 1; }
          unzip a.zip || { echo 'Unzip failed'; exit 1; }
          mv ./bin $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin || { echo 'Move bin failed'; exit 1; }
          mv ./include $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include || { echo 'Move include failed'; exit 1; }

      - name: Build Project
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          retention-days: 30
